apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-spring-petclinic-web-app
  namespace: dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-spring-petclinic-web-app
#    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/gorkemozlu/spring-petclinic-tap
      ref:
        branch: main
